# Generated by Django 6.0.6 on 2026-07-27 16:57

import apps.aziende.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('ragione_sociale', models.TextField(blank=True, db_column='RagioneSociale', null=True)),
                ('indirizzo', models.TextField(blank=True, db_column='Indirizzo', null=True)),
                ('localita', models.TextField(blank=True, db_column='Localita', null=True)),
                ('provincia', models.TextField(blank=True, db_column='Provincia', null=True)),
                ('cap', models.TextField(blank=True, db_column='Cap', null=True)),
                ('partita_iva', models.TextField(blank=True, db_column='PartitaIva', null=True)),
                ('codice_fiscale', models.TextField(blank=True, db_column='CodiceFiscale', null=True)),
                ('telefono', models.TextField(blank=True, db_column='Telefono', null=True)),
                ('fax', models.TextField(blank=True, db_column='Fax', null=True)),
                ('email', models.TextField(blank=True, db_column='email', null=True)),
                ('email_pec', models.TextField(blank=True, db_column='Email_PEC', null=True)),
                ('anno_competenza', models.TextField(blank=True, db_column='AnnoCompetenza', null=True)),
                ('cod_attivita', models.TextField(blank=True, db_column='CodAttivita', null=True)),
                ('desc_attivita', models.TextField(blank=True, db_column='DescAttivita', null=True)),
                ('note', models.TextField(blank=True, db_column='Note', null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Azienda',
                'verbose_name_plural': 'Aziende',
                'db_table': 'aziende',
                'ordering': ['ragione_sociale', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AziendaDati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('azienda_id', models.PositiveIntegerField(db_index=True, help_text="Riferimento all'ID della tabella mirror aziende.", unique=True, verbose_name='ID azienda 4D')),
                ('logo', models.ImageField(blank=True, help_text='Formato PNG o JPG.', null=True, upload_to=apps.aziende.models.azienda_logo_upload_to, verbose_name='Logo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Dati locali azienda',
                'verbose_name_plural': 'Dati locali aziende',
                'ordering': ['azienda_id'],
            },
        ),
    ]
