# Generated by Django 6.0.6 on 2026-07-26 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('sigla', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Sigla')),
                ('codice_istat', models.CharField(max_length=3, unique=True, verbose_name='Codice ISTAT')),
                ('nome', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Provincia',
                'verbose_name_plural': 'Province',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Regione',
            fields=[
                ('codice', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Codice ISTAT')),
                ('nome', models.CharField(db_index=True, max_length=100, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Regione',
                'verbose_name_plural': 'Regioni',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('codice_istat', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Codice ISTAT')),
                ('nome', models.CharField(db_index=True, max_length=150, verbose_name='Nome')),
                ('cap', models.CharField(blank=True, db_index=True, max_length=5, verbose_name='CAP principale')),
                ('codice_catastale', models.CharField(blank=True, db_index=True, max_length=4, verbose_name='Codice catastale')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citta', to='geografia.provincia', verbose_name='Provincia')),
            ],
            options={
                'verbose_name': 'Città',
                'verbose_name_plural': 'Città',
                'ordering': ['nome', 'codice_istat'],
            },
        ),
        migrations.AddField(
            model_name='provincia',
            name='regione',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='province', to='geografia.regione', verbose_name='Regione'),
        ),
    ]
