# Generated by Django 6.0.6 on 2026-07-23 09:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurazione4D',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('attiva', models.BooleanField(default=False, verbose_name='Attiva')),
                ('server', models.CharField(blank=True, help_text='IP o hostname del 4D Server (es. 192.168.1.50).', max_length=300, verbose_name='Server 4D')),
                ('porta', models.PositiveIntegerField(default=19812, help_text='Porta SQL di 4D Server (default 19812).', verbose_name='Porta SQL')),
                ('utente', models.CharField(blank=True, max_length=200, verbose_name='Utente')),
                ('password', models.CharField(blank=True, max_length=200, verbose_name='Password')),
                ('driver_odbc', models.CharField(blank=True, help_text='Lascia vuoto per rilevamento automatico (es. 4D ODBC Driver 64-bit).', max_length=200, verbose_name='Driver ODBC')),
                ('usa_ssl', models.BooleanField(default=False, help_text='Abilita solo se SQL Server di 4D è configurato con SSL.', verbose_name='Usa SSL')),
                ('dsn', models.CharField(blank=True, help_text='Opzionale: se valorizzato, la connessione usa il DSN invece di server/porta.', max_length=200, verbose_name='DSN ODBC')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurazione4d_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurazione4d_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configurazione4d_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Configurazione 4D',
                'verbose_name_plural': 'Configurazioni 4D',
                'permissions': [('access_parametri_4d', 'Può gestire Parametri 4D')],
            },
        ),
    ]
