# Generated by Django 6.0.6 on 2026-07-23 12:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurazione4d',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da'),
        ),
        migrations.AlterField(
            model_name='configurazione4d',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da'),
        ),
        migrations.AlterField(
            model_name='configurazione4d',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da'),
        ),
        migrations.CreateModel(
            name='ComandoVocale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('frase', models.CharField(help_text='Testo da riconoscere, es. "apri clienti" o "cerca cliente".', max_length=200, verbose_name='Frase')),
                ('azione', models.CharField(choices=[('navigate', 'Apri pagina'), ('search', 'Cerca')], max_length=20, verbose_name='Azione')),
                ('destinazione', models.CharField(choices=[('dashboard', 'Dashboard'), ('clienti', 'Clienti'), ('fornitori', 'Fornitori'), ('agenti', 'Agenti'), ('articoli', 'Articoli'), ('fatture', 'Fatture'), ('categorie', 'Categorie'), ('gruppi_articoli', 'Gruppi articoli'), ('parametri_4d', 'Parametri 4D'), ('sistema', 'Sistema'), ('sync_fatture', 'Sync fatture 4D'), ('sync_anagrafiche', 'Sync anagrafiche 4D'), ('sync_categorie', 'Sync categorie 4D'), ('sync_gruppi_articoli', 'Sync gruppi articoli 4D')], max_length=40, verbose_name='Destinazione')),
                ('query', models.CharField(blank=True, help_text='Solo per azione "Cerca": query fissa. Lascia vuoto per usare il testo dopo la frase.', max_length=200, verbose_name='Query di ricerca')),
                ('attivo', models.BooleanField(default=True, verbose_name='Attivo')),
                ('ordine', models.IntegerField(default=0, verbose_name='Ordine')),
                ('match_mode', models.CharField(choices=[('contains', 'Contiene'), ('exact', 'Esatto'), ('starts_with', 'Inizia con')], default='contains', max_length=20, verbose_name='Modalità di match')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Comando vocale',
                'verbose_name_plural': 'Comandi vocali',
                'ordering': ['ordine', 'frase'],
            },
        ),
    ]
