# Generated by Django 6.0.6 on 2026-08-12 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('codice', models.CharField(help_text='Codice breve: ORV, ORA, PRV, DDT, FAT, NCR, NDB, …', max_length=8, primary_key=True, serialize=False, verbose_name='TipoDoc')),
                ('label', models.CharField(max_length=120)),
                ('descrizione', models.TextField(blank=True)),
                ('attivo', models.BooleanField(default=True)),
                ('ordine', models.PositiveSmallIntegerField(default=0)),
                ('source_table_4d', models.CharField(blank=True, max_length=80)),
                ('source_detail_4d', models.CharField(blank=True, max_length=80)),
                ('clifor_tipo', models.CharField(blank=True, choices=[('C', 'Cliente'), ('F', 'Fornitore')], max_length=1)),
            ],
            options={
                'verbose_name': 'Tipo documento',
                'verbose_name_plural': 'Tipi documento',
                'ordering': ['ordine', 'codice'],
            },
        ),
        migrations.CreateModel(
            name='SyncDocumentiLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('teste_count', models.PositiveIntegerField(default=0)),
                ('righe_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_documenti_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log sync documenti',
                'verbose_name_plural': 'Log sync documenti',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TestaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_4d', models.IntegerField(db_index=True)),
                ('source_table_4d', models.CharField(blank=True, max_length=80)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('alfa', models.TextField(blank=True)),
                ('data_documento', models.DateTimeField(blank=True, null=True)),
                ('codice_clifor', models.TextField(blank=True)),
                ('clifor_tipo', models.CharField(blank=True, choices=[('C', 'Cliente'), ('F', 'Fornitore')], max_length=1)),
                ('destinatario', models.TextField(blank=True)),
                ('indirizzo', models.TextField(blank=True)),
                ('localita', models.TextField(blank=True)),
                ('cap', models.TextField(blank=True)),
                ('provincia', models.TextField(blank=True)),
                ('nazione', models.TextField(blank=True)),
                ('cod_iso_dest', models.TextField(blank=True)),
                ('totale', models.FloatField(blank=True, null=True)),
                ('imponibile', models.FloatField(blank=True, null=True)),
                ('spese_imballo', models.FloatField(blank=True, null=True)),
                ('spese_trasporto', models.FloatField(blank=True, null=True)),
                ('spese_incasso', models.FloatField(blank=True, null=True)),
                ('spese_varie', models.FloatField(blank=True, null=True)),
                ('spese_bolli', models.FloatField(blank=True, null=True)),
                ('spese_e15', models.FloatField(blank=True, null=True)),
                ('imp_spese_bollo_virtuale', models.FloatField(blank=True, null=True)),
                ('tipo_doc_fe', models.TextField(blank=True)),
                ('cod_sdi', models.TextField(blank=True)),
                ('progressivo_invio', models.IntegerField(blank=True, null=True)),
                ('email_pec', models.TextField(blank=True)),
                ('file_name', models.TextField(blank=True)),
                ('iban', models.TextField(blank=True)),
                ('cod_pagamento', models.TextField(blank=True)),
                ('cig', models.TextField(blank=True)),
                ('cup', models.TextField(blank=True)),
                ('num_ordine_acq', models.TextField(blank=True)),
                ('data_ordine_acq', models.DateTimeField(blank=True, null=True)),
                ('desc_causale', models.TextField(blank=True)),
                ('desc_nota_c', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('tipo_doc', models.ForeignKey(db_column='tipo_doc', on_delete=django.db.models.deletion.PROTECT, related_name='teste', to='documenti.tipodocumento')),
            ],
            options={
                'verbose_name': 'Testata documento',
                'verbose_name_plural': 'Testate documenti',
                'db_table': 'teste_documenti',
                'ordering': ['-data_documento', '-numero', '-id_4d'],
            },
        ),
        migrations.CreateModel(
            name='RigaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_4d', models.IntegerField()),
                ('id_riga', models.IntegerField(blank=True, null=True)),
                ('numero_riga', models.IntegerField(blank=True, null=True)),
                ('codice', models.TextField(blank=True)),
                ('descrizione', models.TextField(blank=True)),
                ('quantita', models.FloatField(blank=True, null=True)),
                ('prezzo_unitario', models.FloatField(blank=True, null=True)),
                ('iva', models.TextField(blank=True)),
                ('unita_misura', models.TextField(blank=True)),
                ('sconto', models.TextField(blank=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
                ('testa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='documenti.testadocumento')),
            ],
            options={
                'verbose_name': 'Riga documento',
                'verbose_name_plural': 'Righe documenti',
                'db_table': 'righe_documenti',
                'ordering': ['testa_id', 'numero_riga', 'id_4d'],
                'constraints': [models.UniqueConstraint(fields=('testa', 'id_4d'), name='uniq_riga_testa_id4d')],
            },
        ),
        migrations.AddIndex(
            model_name='testadocumento',
            index=models.Index(fields=['tipo_doc', 'data_documento'], name='teste_docum_tipo_do_6cc823_idx'),
        ),
        migrations.AddIndex(
            model_name='testadocumento',
            index=models.Index(fields=['codice_clifor'], name='teste_docum_codice__52d0fc_idx'),
        ),
        migrations.AddConstraint(
            model_name='testadocumento',
            constraint=models.UniqueConstraint(fields=('tipo_doc', 'id_4d'), name='uniq_testa_tipo_id4d'),
        ),
    ]
