# Generated by Django 6.0.6 on 2026-08-13 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0005_colonne_riga_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colonnarigadocumento',
            name='tipo_doc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colonne_riga', to='documenti.tipodocumento'),
        ),
    ]
