# Generated by Django 6.0.6 on 2026-08-14 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documenti', '0010_scadenze_lista'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoreDocumento',
            fields=[
                ('codice', models.CharField(help_text='Codice breve univoco (es. FAT, ORD, DDT1).', max_length=16, primary_key=True, serialize=False, verbose_name='Codice')),
                ('label', models.CharField(max_length=120, verbose_name='Descrizione')),
                ('ultimo_numero', models.PositiveIntegerField(default=0, help_text='Ultimo numero assegnato. Il prossimo documento riceve ultimo_numero + 1.', verbose_name='Ultimo numero')),
                ('serie_default', models.CharField(blank=True, help_text='Opzionale: valorizzata sul documento in creazione se la serie è vuota.', max_length=16, verbose_name='Serie predefinita')),
            ],
            options={
                'verbose_name': 'Contatore documento',
                'verbose_name_plural': 'Contatori documento',
                'db_table': 'contatori_documento',
                'ordering': ['codice'],
            },
        ),
        migrations.AddField(
            model_name='tipodocumento',
            name='contatore',
            field=models.ForeignKey(blank=True, help_text='Contatore da cui assegnare il numero in creazione. Vuoto = numerazione automatica per tipo (comportamento precedente).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tipi_documento', to='documenti.contatoredocumento', verbose_name='Contatore'),
        ),
    ]
