# Generated by Django 6.0.6 on 2026-08-18

from django.utils import timezone

from django.db import migrations, models


def _default_esercizio() -> int:
    return timezone.localdate().year


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0030_tipodocumento_testo_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="contatoredocumento",
            name="esercizio",
            field=models.PositiveSmallIntegerField(
                default=_default_esercizio,
                help_text="Anno contabile/fiscale di riferimento per la numerazione.",
                verbose_name="Esercizio",
            ),
        ),
        migrations.AlterModelOptions(
            name="contatoredocumento",
            options={
                "ordering": ["esercizio", "codice"],
                "verbose_name": "Contatore documento",
                "verbose_name_plural": "Contatori documento",
            },
        ),
    ]
