# Generated by Django 6.0.6 on 2026-08-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0032_contatoredocumento_esercizio_repair"),
    ]

    operations = [
        migrations.AddField(
            model_name="contatoredocumento",
            name="tipo_contatore",
            field=models.CharField(
                choices=[("DOCUMENTI", "Documenti"), ("PRIMANOTA", "Primanota")],
                db_index=True,
                default="DOCUMENTI",
                help_text="Ambito di utilizzo: numerazione documenti o primanota.",
                max_length=16,
                verbose_name="Tipo contatore",
            ),
        ),
        migrations.AlterModelOptions(
            name="contatoredocumento",
            options={
                "ordering": ["tipo_contatore", "esercizio", "codice"],
                "verbose_name": "Contatore documento",
                "verbose_name_plural": "Contatori documento",
            },
        ),
    ]
