# Generated by Django 6.0.6 on 2026-08-18

import apps.documenti.models
from django.db import migrations, models


def _quote(name: str) -> str:
    return '"' + name.replace('"', '""') + '"'


def _pg_drop_fks(cursor, table: str, column: str) -> None:
    cursor.execute(
        """
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        JOIN pg_namespace nsp ON nsp.oid = rel.relnamespace
        JOIN pg_attribute att
          ON att.attrelid = rel.oid AND att.attnum = ANY (con.conkey)
        WHERE con.contype = 'f'
          AND rel.relname = %s
          AND att.attname = %s
        """,
        [table, column],
    )
    for (name,) in cursor.fetchall():
        cursor.execute(f"ALTER TABLE {_quote(table)} DROP CONSTRAINT {_quote(name)}")


def _pg_drop_pk(cursor, table: str) -> None:
    cursor.execute(
        """
        SELECT con.conname
        FROM pg_constraint con
        JOIN pg_class rel ON rel.oid = con.conrelid
        WHERE con.contype = 'p' AND rel.relname = %s
        """,
        [table],
    )
    row = cursor.fetchone()
    if row:
        cursor.execute(f"ALTER TABLE {_quote(table)} DROP CONSTRAINT {_quote(row[0])}")


def rebuild_contatore_pk(apps, schema_editor):
    connection = schema_editor.connection
    vendor = connection.vendor
    with connection.cursor() as cursor:
        columns = {
            col.name: col
            for col in connection.introspection.get_table_description(
                cursor, "contatori_documento"
            )
        }
        if vendor == "postgresql":
            _rebuild_postgres(cursor, columns)
        else:
            if "id" in columns:
                return
            _rebuild_sqlite(cursor)


def _rebuild_postgres(cursor, columns: dict) -> None:
    if "id" not in columns:
        _pg_drop_fks(cursor, "parametri_documento", "contatore_id")
        cursor.execute(
            "SELECT to_regclass('public.parametri_documento_contatori')"
        )
        has_m2m = cursor.fetchone()[0] is not None
        if has_m2m:
            _pg_drop_fks(
                cursor, "parametri_documento_contatori", "contatoredocumento_id"
            )

        cursor.execute("ALTER TABLE contatori_documento ADD COLUMN id bigint")
        cursor.execute("CREATE SEQUENCE IF NOT EXISTS contatori_documento_id_seq")
        cursor.execute(
            "UPDATE contatori_documento SET id = nextval('contatori_documento_id_seq') "
            "WHERE id IS NULL"
        )
        cursor.execute(
            "ALTER TABLE contatori_documento ALTER COLUMN id SET DEFAULT "
            "nextval('contatori_documento_id_seq')"
        )
        cursor.execute("ALTER TABLE contatori_documento ALTER COLUMN id SET NOT NULL")
        cursor.execute(
            "ALTER SEQUENCE contatori_documento_id_seq OWNED BY contatori_documento.id"
        )
        cursor.execute(
            "SELECT setval('contatori_documento_id_seq', "
            "COALESCE((SELECT MAX(id) FROM contatori_documento), 1))"
        )
        _pg_drop_pk(cursor, "contatori_documento")
        cursor.execute("ALTER TABLE contatori_documento ADD PRIMARY KEY (id)")

    cursor.execute(
        "CREATE UNIQUE INDEX IF NOT EXISTS uniq_contatore_codice_esercizio_tipo "
        "ON contatori_documento (codice, esercizio, tipo_contatore)"
    )

    cursor.execute(
        """
        SELECT data_type FROM information_schema.columns
        WHERE table_name = 'parametri_documento' AND column_name = 'contatore_id'
        """
    )
    row = cursor.fetchone()
    contatore_type = (row[0] if row else "") or ""
    if row and contatore_type in ("character varying", "text", "varchar"):
        _pg_drop_fks(cursor, "parametri_documento", "contatore_id")
        cursor.execute(
            "ALTER TABLE parametri_documento ADD COLUMN IF NOT EXISTS "
            "contatore_id_new bigint"
        )
        cursor.execute(
            """
            UPDATE parametri_documento p
            SET contatore_id_new = c.id
            FROM contatori_documento c
            WHERE p.contatore_id IS NOT NULL AND p.contatore_id = c.codice
            """
        )
        cursor.execute("ALTER TABLE parametri_documento DROP COLUMN contatore_id")
        cursor.execute(
            "ALTER TABLE parametri_documento RENAME COLUMN contatore_id_new "
            "TO contatore_id"
        )
        contatore_type = "bigint"

    if row:
        cursor.execute(
            """
            SELECT 1 FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            WHERE con.contype = 'f' AND rel.relname = 'parametri_documento'
              AND con.conname = 'documenti_tipodocumento_contatore_id_fk'
            """
        )
        if cursor.fetchone() is None:
            cursor.execute(
                "ALTER TABLE parametri_documento "
                "ADD CONSTRAINT documenti_tipodocumento_contatore_id_fk "
                "FOREIGN KEY (contatore_id) REFERENCES contatori_documento(id) "
                "ON DELETE RESTRICT DEFERRABLE INITIALLY DEFERRED"
            )

    cursor.execute(
        "SELECT to_regclass('public.parametri_documento_contatori')"
    )
    if cursor.fetchone()[0] is None:
        return
    cursor.execute(
        """
        SELECT data_type FROM information_schema.columns
        WHERE table_name = 'parametri_documento_contatori'
          AND column_name = 'contatoredocumento_id'
        """
    )
    m2m_type_row = cursor.fetchone()
    m2m_type = (m2m_type_row[0] if m2m_type_row else "") or ""
    if m2m_type_row and m2m_type in ("character varying", "text", "varchar"):
        _pg_drop_fks(
            cursor, "parametri_documento_contatori", "contatoredocumento_id"
        )
        cursor.execute(
            "ALTER TABLE parametri_documento_contatori "
            "ADD COLUMN IF NOT EXISTS contatoredocumento_id_new bigint"
        )
        cursor.execute(
            """
            UPDATE parametri_documento_contatori m
            SET contatoredocumento_id_new = c.id
            FROM contatori_documento c
            WHERE m.contatoredocumento_id = c.codice
            """
        )
        cursor.execute(
            "ALTER TABLE parametri_documento_contatori "
            "DROP COLUMN contatoredocumento_id"
        )
        cursor.execute(
            "ALTER TABLE parametri_documento_contatori "
            "RENAME COLUMN contatoredocumento_id_new TO contatoredocumento_id"
        )
        cursor.execute(
            "ALTER TABLE parametri_documento_contatori "
            "ALTER COLUMN contatoredocumento_id SET NOT NULL"
        )
        m2m_type = "bigint"
    if m2m_type_row:
        cursor.execute(
            """
            SELECT 1 FROM pg_constraint con
            JOIN pg_class rel ON rel.oid = con.conrelid
            WHERE con.contype = 'f'
              AND rel.relname = 'parametri_documento_contatori'
              AND con.conname = 'parametri_documento_contatori_contatore_fk'
            """
        )
        if cursor.fetchone() is None:
            cursor.execute(
                "ALTER TABLE parametri_documento_contatori "
                "ADD CONSTRAINT parametri_documento_contatori_contatore_fk "
                "FOREIGN KEY (contatoredocumento_id) REFERENCES contatori_documento(id) "
                "ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED"
            )


def _rebuild_sqlite(cursor) -> None:
    cursor.execute("PRAGMA foreign_keys=OFF")
    cursor.execute(
        """
        CREATE TABLE contatori_documento__new (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            codice varchar(16) NOT NULL,
            label varchar(120) NOT NULL,
            tipo_contatore varchar(16) NOT NULL,
            esercizio smallint NOT NULL,
            ultimo_numero integer unsigned NOT NULL,
            serie_default varchar(16) NOT NULL
        )
        """
    )
    cursor.execute(
        """
        INSERT INTO contatori_documento__new
            (codice, label, tipo_contatore, esercizio, ultimo_numero, serie_default)
        SELECT codice, label, tipo_contatore, esercizio, ultimo_numero, serie_default
        FROM contatori_documento
        """
    )
    cursor.execute("DROP TABLE contatori_documento")
    cursor.execute(
        "ALTER TABLE contatori_documento__new RENAME TO contatori_documento"
    )
    cursor.execute(
        "CREATE UNIQUE INDEX uniq_contatore_codice_esercizio_tipo "
        "ON contatori_documento (codice, esercizio, tipo_contatore)"
    )

    cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name='parametri_documento'"
    )
    if cursor.fetchone():
        _sqlite_rebuild_parametri(cursor)

    cursor.execute(
        "SELECT name FROM sqlite_master WHERE type='table' "
        "AND name='parametri_documento_contatori'"
    )
    if cursor.fetchone():
        cursor.execute(
            """
            CREATE TABLE parametri_documento_contatori__new (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                tipodocumento_id varchar(8) NOT NULL,
                contatoredocumento_id bigint NOT NULL,
                UNIQUE (tipodocumento_id, contatoredocumento_id)
            )
            """
        )
        cursor.execute(
            """
            INSERT INTO parametri_documento_contatori__new
                (id, tipodocumento_id, contatoredocumento_id)
            SELECT
                m.id,
                m.tipodocumento_id,
                c.id
            FROM parametri_documento_contatori m
            JOIN contatori_documento c
              ON CAST(c.codice AS TEXT) = CAST(m.contatoredocumento_id AS TEXT)
            """
        )
        cursor.execute("DROP TABLE parametri_documento_contatori")
        cursor.execute(
            "ALTER TABLE parametri_documento_contatori__new "
            "RENAME TO parametri_documento_contatori"
        )
    cursor.execute("PRAGMA foreign_keys=ON")


def _sqlite_rebuild_parametri(cursor) -> None:
    cursor.execute("PRAGMA table_info(parametri_documento)")
    cols = cursor.fetchall()
    parts = []
    pk_cols = []
    select_cols = []
    for _cid, name, ctype, notnull, dflt, pk in cols:
        if name == "contatore_id":
            ctype = "bigint"
            select_cols.append(
                "(SELECT c.id FROM contatori_documento c "
                'WHERE CAST(c.codice AS TEXT) = CAST(p.contatore_id AS TEXT))'
            )
        else:
            select_cols.append(f'p."{name}"')
        spec = f'"{name}" {ctype or "TEXT"}'
        if notnull and name != "contatore_id":
            spec += " NOT NULL"
        if dflt is not None:
            spec += f" DEFAULT {dflt}"
        parts.append(spec)
        if pk:
            pk_cols.append(f'"{name}"')
    create_sql = "CREATE TABLE parametri_documento__new (" + ", ".join(parts)
    if pk_cols:
        create_sql += f", PRIMARY KEY ({', '.join(pk_cols)})"
    create_sql += ")"
    cursor.execute(create_sql)
    cursor.execute(
        "INSERT INTO parametri_documento__new SELECT "
        + ", ".join(select_cols)
        + " FROM parametri_documento p"
    )
    cursor.execute("DROP TABLE parametri_documento")
    cursor.execute(
        "ALTER TABLE parametri_documento__new RENAME TO parametri_documento"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("documenti", "0033_contatoredocumento_tipo_contatore"),
    ]

    operations = [
        migrations.CreateModel(
            name="Porto",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        db_column="ID", primary_key=True, serialize=False
                    ),
                ),
                (
                    "cod_incoterm",
                    models.TextField(
                        blank=True, db_column="Cod_Incoterm", null=True
                    ),
                ),
                (
                    "descrizione",
                    models.TextField(
                        blank=True, db_column="Descrizione", null=True
                    ),
                ),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Porto",
                "verbose_name_plural": "Porti",
                "db_table": "tab_porto",
                "ordering": ["descrizione", "id"],
                "managed": False,
            },
        ),
        migrations.AlterModelOptions(
            name="testadocumento",
            options={
                "ordering": ["-data_documento", "-numero", "alfa", "-id_4d"],
                "verbose_name": "Testata documento",
                "verbose_name_plural": "Testate documenti",
            },
        ),
        migrations.AlterField(
            model_name="colonnarigadocumento",
            name="campo",
            field=models.CharField(
                choices=[
                    ("numero_riga", "#"),
                    ("codice", "Codice"),
                    ("descrizione", "Descrizione"),
                    ("quantita", "Qtà"),
                    ("unita_misura", "U.M."),
                    ("prezzo_unitario", "Prezzo"),
                    ("sconto", "Sconto"),
                    ("provvigione", "Provvigione"),
                    ("iva", "IVA"),
                ],
                max_length=40,
                verbose_name="Campo",
            ),
        ),
        migrations.AlterField(
            model_name="contatoredocumento",
            name="esercizio",
            field=models.PositiveSmallIntegerField(
                default=apps.documenti.models._default_esercizio,
                help_text="Anno contabile/fiscale di riferimento per la numerazione.",
                verbose_name="Esercizio",
            ),
        ),
        migrations.AlterField(
            model_name="tipodocumento",
            name="contatori",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "Contatori selezionabili nella maschera documento (combo Serie), "
                    "uniti a quelli dei tipi affini (es. Preventivi↔Ordini). "
                    "Il Contatore predefinito è usato all'apertura di Nuovo."
                ),
                related_name="tipi_documento_multi",
                to="documenti.contatoredocumento",
                verbose_name="Contatori / serie",
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(rebuild_contatore_pk, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AddField(
                    model_name="contatoredocumento",
                    name="id",
                    field=models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                migrations.AlterField(
                    model_name="contatoredocumento",
                    name="codice",
                    field=models.CharField(
                        db_index=True,
                        help_text=(
                            "Codice breve (es. FAT, ORD, PN). "
                            "Univoco insieme a esercizio e tipo."
                        ),
                        max_length=16,
                        verbose_name="Codice",
                    ),
                ),
                migrations.AddConstraint(
                    model_name="contatoredocumento",
                    constraint=models.UniqueConstraint(
                        fields=("codice", "esercizio", "tipo_contatore"),
                        name="uniq_contatore_codice_esercizio_tipo",
                    ),
                ),
            ],
        ),
    ]
