# Generated by Django 6.0.6 on 2026-07-27 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedaLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('data', models.DateField(verbose_name='Data')),
                ('operatore_codice', models.CharField(max_length=50, verbose_name='Codice operatore')),
                ('operatore_nome', models.CharField(blank=True, max_length=200, verbose_name='Operatore')),
                ('matricola', models.CharField(blank=True, max_length=50, verbose_name='Matricola')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Scheda di lavorazione',
                'verbose_name_plural': 'Schede di lavorazione',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RigaSchedaLavorazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('ordine', models.PositiveIntegerField(default=1, verbose_name='Ordine')),
                ('codice_pezzo', models.CharField(max_length=80, verbose_name='Codice pezzo')),
                ('cliente', models.CharField(blank=True, max_length=80, verbose_name='Cliente')),
                ('cod_art_cliente', models.CharField(blank=True, max_length=80, verbose_name='Cod. Art. Cliente')),
                ('descrizione_componente', models.CharField(blank=True, max_length=500, verbose_name='Descrizione componente')),
                ('tempo_distinta', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tempo distinta')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
                ('scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='righe', to='schede_lavorazione.schedalavorazione', verbose_name='Scheda')),
            ],
            options={
                'verbose_name': 'Riga scheda di lavorazione',
                'verbose_name_plural': 'Righe scheda di lavorazione',
                'ordering': ['ordine', 'id'],
            },
        ),
    ]
