# Generated by Django 6.0.6 on 2026-07-23 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fattura',
            fields=[
                ('id_testa', models.IntegerField(db_column='ID_Testa', primary_key=True, serialize=False)),
                ('numero_fatt', models.IntegerField(blank=True, db_column='NumeroFatt', null=True)),
                ('data_fattura', models.DateTimeField(blank=True, db_column='DataFattura', null=True)),
                ('cliente', models.TextField(blank=True, db_column='Cliente', null=True)),
                ('destinatario', models.TextField(blank=True, db_column='Destinatario', null=True)),
                ('totale_fattura', models.FloatField(blank=True, db_column='TotaleFattura', null=True)),
                ('imponibile', models.FloatField(blank=True, db_column='Imponibile', null=True)),
                ('alfa', models.TextField(blank=True, db_column='Alfa', null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Fattura',
                'verbose_name_plural': 'Fatture',
                'db_table': 'fatture',
                'ordering': ['-data_fattura', '-numero_fatt'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FatturaDettaglio',
            fields=[
                ('id', models.IntegerField(db_column='ID', primary_key=True, serialize=False)),
                ('id_testa', models.IntegerField(blank=True, db_column='id_added_by_converter', db_index=True, null=True, verbose_name='ID testa fattura')),
                ('id_riga', models.IntegerField(blank=True, db_column='ID_Riga', null=True)),
                ('codice', models.TextField(blank=True, db_column='Codice', null=True)),
                ('descrizione', models.TextField(blank=True, db_column='DescAgg', null=True)),
                ('quantita', models.FloatField(blank=True, db_column='Quantita', null=True)),
                ('prezzo_unitario', models.FloatField(blank=True, db_column='PrezzoUnitario', null=True)),
                ('iva', models.TextField(blank=True, db_column='Iva', null=True)),
                ('numero_riga', models.IntegerField(blank=True, db_column='NumeroRiga', null=True)),
                ('synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Riga fattura',
                'verbose_name_plural': 'Righe fattura',
                'db_table': 'fatture_dettaglio',
                'ordering': ['id_testa', 'numero_riga', 'id'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SyncFattureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('ok', models.BooleanField(default=False)),
                ('fatture_count', models.PositiveIntegerField(default=0)),
                ('dettaglio_count', models.PositiveIntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_fatture_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log sync fatture',
                'verbose_name_plural': 'Log sync fatture',
                'ordering': ['-started_at'],
            },
        ),
    ]
