# Generated by Django 6.0.6 on 2026-07-27 16:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creato il')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificato il')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Eliminato il')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('note', models.TextField(blank=True, verbose_name='Note')),
                ('titolo', models.CharField(max_length=200, verbose_name='Titolo')),
                ('descrizione', models.TextField(blank=True, verbose_name='Descrizione')),
                ('inizio', models.DateTimeField(verbose_name='Inizio')),
                ('fine', models.DateTimeField(verbose_name='Fine')),
                ('tutto_il_giorno', models.BooleanField(default=False, verbose_name='Tutto il giorno')),
                ('luogo', models.CharField(blank=True, max_length=200, verbose_name='Luogo')),
                ('colore', models.CharField(choices=[('#3b82f6', 'Blu'), ('#22c55e', 'Verde'), ('#ef4444', 'Rosso'), ('#f97316', 'Arancione'), ('#a855f7', 'Viola'), ('#14b8a6', 'Teal'), ('#ec4899', 'Rosa'), ('#64748b', 'Grigio')], default='#3b82f6', max_length=20, verbose_name='Colore')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Eliminato da')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='Modificato da')),
            ],
            options={
                'verbose_name': 'Evento agenda',
                'verbose_name_plural': 'Eventi agenda',
                'ordering': ['inizio', 'id'],
                'indexes': [models.Index(fields=['inizio', 'fine'], name='agenda_even_inizio_40f329_idx'), models.Index(fields=['is_active', 'inizio'], name='agenda_even_is_acti_24a154_idx')],
            },
        ),
    ]
